server:
  port: 9998

  application:
    name: battle

spring:
  datasource:
    url: jdbc:postgresql://0.0.0.0:5433/game
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        jdbc:
          lob:
            non_contextual_creation: true