server:
  port: 9998

spring:
  datasource:
    url: jdbc:postgresql://0.0.0.0:5433/game
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        jdbc:
          lob:
            non_contextual_creation: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  cloud:
    stream:
      bindings:
        battle-event-supplier-out-0:
          destination: battle-events