version: '3.9'
services:
  postgres:
    container_name: postgres
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_DB: 'security'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
    ports:
      - '5432:5432'
