server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin

#logging:
#  level:
#    root: DEBUG
#    org.springframework.web: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.security.oauth2: DEBUG