server:
  port: 9997

  application:
    name: statistic

spring:
  cloud:
    stream:
      bindings:
        consumeBattleFinishedEvent-in-0:
          destination: battle-events
      function:
        definition: consumeBattleFinishedEvent;

  datasource:
    url: jdbc:postgresql://0.0.0.0:5434/statistic
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true