version: '3.9'
services:
  postgres:
    container_name: postgres2
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_DB: 'game'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
    ports:
      - '5433:5432'
