version: '3.9'
services:
  postgres:
    container_name: postgres3
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_DB: 'statistic'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
    ports:
      - '5434:5432'